### ISSUE TITLE
legalEntity from D365 F&O trigger should be parameterized 

### ISSUE THREAD

**Issue by linuswaerner** [jeffhollan/LogicAppTemplateCreator#101]
Hi!

When extracting a logic app triggered by the D365 Fin&Ops connector, there's a parameter called LegalEntity. This is not parameterized upon extraction:
```

          "triggers": {
            "When_a_Business_Event_occurs": {
              "type": "ApiConnectionWebhook",
              "inputs": {
                "body": {
                  "NotificationUrl": "@{listCallbackUrl()}"
                },
                "host": {
                  "connection": {
                    "name": "@parameters('$connections')['dynamicsax']['connectionId']"
                  }
                },
                "path": "my_path_is_here",
                "queries": {
                  "businesseventcategory": "Alerts",
                  "legalEntity": "<THIS_PARAMETER>"
                }
              }
            }
```
What I refer to is the property marked with "<THIS_PARAMETER>".

This also applies to the "List all items in table"-actions and such, where Odata filter is applied using a pre-defined parameter. It would be extremely useful to be able to parameterize these, since it would make it possible to dynamically set filters during deploy.

Cheers!

**Comment by MLogdberg** [comment]
This should be solved
