### ISSUE TITLE
audience in http authentication (ManagedServiceIdentity) could be null

### ISSUE THREAD

**Issue by KreizIT** [jeffhollan/LogicAppTemplateCreator#105]
Regex.IsMatch crash if audience is null

https://github.com/jeffhollan/LogicAppTemplateCreator/blob/4e18094fb186e86c37661aef03f68d1827c938df/LogicAppTemplate/TemplateGenerator.cs#L488

**Comment by MLogdberg** [comment]
Merged the fix, thanks for reporting in! #109
