### ISSUE TITLE
Error AggregateException

### ISSUE THREAD

**Issue by dgrospelier** [jeffhollan/LogicAppTemplateCreator#19]
Hi,
When I use the PowerShell cmdlets, I got a AggregateException in the ProcessRecord method.
There is an innerException of type ArgumentTypeException with the message 'String cannot be of zero length. Parameter name oldValue.

I have this error with one of my Logic App. This is one Logic App with a recurrence as a trigger and multiple File System connectors and an OnPremise Data Gateway connection. Maybe this can help ?

**Comment by MLogdberg** [comment]
Hi dgrospelier, thanks for reporting this.
To me it looks like there is an issue with how we generate the template for List Files in Folder.
I'll add a test for it and push a fix that you could try, I'll let you know when it's ready.

**Comment by dgrospelier** [comment]
Hi Mattias,
I now have the same issue with a couple of other logic apps.
In fact, only one of my Logic App is exported, all other logic apps failed with the same issue.

If you want I can send you the JSON of the logic apps so you can try?

**Comment by MLogdberg** [comment]
I've provided an update, there could be an issue with anoither thing, trying to minimnize number of parameters so I removed that aswell.

Please send me the json and try the new updates

**Comment by dgrospelier** [comment]
Can I send the JSON you in DM?

FYI I tried the new version and I still have the same issue.

**Comment by MLogdberg** [comment]
yea just send em in DM or email m.logdberg[at]gmail.com

**Comment by MLogdberg** [comment]
Added a fix for this in the branch https://github.com/jeffhollan/LogicAppTemplateCreator/tree/missingparameter
can you please test this and verify if it's working.
Cheers!

**Comment by MLogdberg** [comment]
Issue has been fixed under branch missingparameter and will be merged.
