### ISSUE TITLE
Boolean parameters are not handled successfully

### ISSUE THREAD

**Issue by dgrospelier** [jeffhollan/LogicAppTemplateCreator#21]
Hi,
When a FTP connection is used by the Logic App for example, there are multiple parameters for this connection that are of type Boolean (i.e isSSL for example).
The value generated in the template for those parameters is not ok: it should be set to false or true and not False or True (the F and T must be in lower case) to be handled correctly in the JSON.

**Comment by MLogdberg** [comment]
Thanks dgrospelier for informing on this, I'll take a look at this.

**Comment by MLogdberg** [comment]
Issue is found and a fix is merged in.
