### ISSUE TITLE
Provide module in Powershell Gallery

### ISSUE THREAD

**Issue by tomkerkhove** [jeffhollan/LogicAppTemplateCreator#26]
Are there plans to provide this module in the PowerShell gallery?

**Comment by MLogdberg** [comment]
There is a version in the PowerShell gallery but I think it's old.
I agree, we need to fix some sort of automatic release to PowerShell Gallery.

**Comment by tomkerkhove** [comment]
Or even get merged into https://docs.microsoft.com/en-us/powershell/module/azurerm.logicapp/?view=azurermps-5.2.0

**Comment by MLogdberg** [comment]
Sounds even better 👍

**Comment by MLogdberg** [comment]
Not included in AzureRM.LogicApp but atleast auto updated to PowerShell Gallery now.
You can find it here:
https://www.powershellgallery.com/packages/LogicAppTemplate/1.0.7

Closing this issue.
