### ISSUE TITLE
Error when calling Get-LogicAppTemplate

### ISSUE THREAD

**Issue by ankurMalhotra** [jeffhollan/LogicAppTemplateCreator#31]
Get the following error:

Get-LogicAppTemplate : Aggregation Exception thrown, One or more errors occurred., first Exception message is: Cannot access child value on Newtonsoft.Json.Linq.JValue., for more information read the out
At line:1 char:1
+ Get-LogicAppTemplate -LogicApp  LogicAppName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LogicAppTemplate], Exception
    + FullyQualifiedErrorId : System.Exception,LogicAppTemplate.GeneratorCmdlet

**Comment by MLogdberg** [comment]
Hi, could you provide abit more information? Like what connectors are you using?
Seems like an error du e to a null value.

If you can add the -DebugOutPutFolder path to get the exported files, you can either debugg it or email the files so I can check it.

**Comment by bkarthika** [comment]
Hi,
  I am getting object reference error.
Get-LogicAppTemplate -LogicApp -...........................

Get-LogicAppTemplate : Aggregation Exception thrown, One or more errors occurred., first Exception message is: Object reference not 
set to an instance of an object., for more information read the output file.
At line:1 char:1
+ Get-LogicAppTemplate -LogicApp NetsuteUpdateShipment -ResourceGroup N ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LogicAppTemplate], Exception
    + FullyQualifiedErrorId : System.Exception,LogicAppTemplate.GeneratorCmdlet

**Comment by bkarthika** [comment]
"If you can add the -DebugOutPutFolder path to get the exported files, you can either debugg it or email the files so I can check it."

How to do this?

**Comment by MLogdberg** [comment]
Here is a sample from my PS script:
Get-LogicAppTemplate -LogicApp $logicapname -ResourceGroup $resourcegroupname -SubscriptionId $subscriptionid -TenantName $tenant -DebugOutPutFolder  "C:\\temp\\Logicapps" | Out-File $filenname

**Comment by MLogdberg** [comment]
#if you have problem with execution policy execute this in a administrator runned powershell window.
#Set-ExecutionPolicy -ExecutionPolicy Unrestricted

Import-Module "C:\Users\Administrator\Desktop\PS Logic Apps\TemplateCreator\LogicAppTemplateCreator\LogicAppTemplate\bin\Debug\LogicAppTemplate.dll"

#Set the name of the Logic App
$logicapname = 'INT001-MyLogicapp'
#Set the resource group of the Logic App
$resourcegroupname = 'Integration'
#Set the subscription id of where the Logic App is
$subscriptionid = 'd4ba21e9-15f5-4c85-bb3e-1e108dc79b00'
#Set the tenant to use with the Logic App, make sure it has the right tennant
$tenant = 'ibiz-solutions.se'

#setting the output filename
$filenname = $logicapname + '.json'
$filennameparam = $logicapname + '.parameters.json'

Get-LogicAppTemplate -LogicApp $logicapname -ResourceGroup $resourcegroupname -SubscriptionId $subscriptionid -TenantName $tenant -DebugOutPutFolder  "C:\\temp\\Logicapps" | Out-File $filenname

**Comment by MLogdberg** [comment]
Also the problem might be as many others that you have not specifying the **tenant** and your account is connected to multiple tenants and the standard sign in is not the tenant where your Logic App is hosted.

**Comment by bkarthika** [comment]
Even after setting Tenant as in above script I am getting the same error.

Get-LogicAppTemplate -LogicApp $logicapname -ResourceGroup $resourcegroupname -SubscriptionId $subscriptionid -TenantName $tenant -DebugOutPutFolder "C:\Templates\Newfolder" | Out-File $filenname
Get-LogicAppTemplate : Aggregation Exception thrown, One or more errors occurred., first Exception message is: Object reference not 
set to an instance of an object., for more information read the output file.
At line:19 char:1
+ Get-LogicAppTemplate -LogicApp $logicapname -ResourceGroup $resourceg ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LogicAppTemplate], Exception
    + FullyQualifiedErrorId : System.Exception,LogicAppTemplate.GeneratorCmdlet

**Comment by MLogdberg** [comment]
Okey, so wthen it might be something with the custom Connector, I'll check that out.

**Comment by ankurMalhotra** [comment]
Yup I was using a custom connector - Http with AAD.
I'l generate the debug file and post it here.

**Comment by KarthikaSamidurai** [comment]
Any updates?

**Comment by MLogdberg** [comment]
Hi I think I've found the issue, could you try again?

**Comment by KarthikaSamidurai** [comment]
Ok. I will try and let you know.

**Comment by KarthikaSamidurai** [comment]
Its working.. Thank you very much.

**Comment by hariharan618** [comment]
I am facing this today. Is this fixed or am i doing something wrong ? I am having my own custom connectors used in the LogicApp

**Comment by mo20096258** [comment]
hi,
is this issue is resolved??? I am also getting the same issue every time

**Comment by KarthikaSamidurai** [comment]
"
Hi,
I am getting object reference error. I am trying to generate template of a logic app thats using custom connector.

"
-- yes this issue is fixed.

**Comment by dgroh** [comment]
when I pass $tenantName I get: 

> 'authority' should be in Uri format

**Comment by simonstender** [comment]
@MLogdberg 
Hi!
I seem to get similar errors when trying to extract logic apps multiple logic apps from a resource group.
`Get-LogicAppTemplate : Aggregation Exception thrown, Ett eller flera fel har uppstått., first Exception message 
is: Objektreferensen har inte angetts till en instans av ett objekt., for more information read the output file.
At P:\Program\LogicAppTemplateExtractor\LogicAppTemplate\Cmdlets\Get-RGLogicAppsTemplate.ps1:60 char:2
+     Get-LogicAppTemplate -LogicApp $_.Name -ResourceGroup $_.Resource ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LogicAppTemplate], Exception
    + FullyQualifiedErrorId : System.Exception,LogicAppTemplate.GeneratorCmdlet
 
Get-ParameterTemplate : Error reading JObject from JsonReader. Path '', line 0, position 0.
At P:\Program\LogicAppTemplateExtractor\LogicAppTemplate\Cmdlets\Get-RGLogicAppsTemplate.ps1:63 char:2
+     Get-ParameterTemplate -TemplateFile $destinationfile | Out-File $ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ParameterTemplate], JsonReaderException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonReaderException,LogicAppTemplate.ParamGenerator`
    
Only the logic apps using custom connectors are the ones causing an error, the logic apps that are not using CC are extracted without any problem.

You know what might cause this?

**Comment by MLogdberg** [comment]
Hi @simonstender sounds strange, I know that Custom Connectors are used i several places. But a nullpointer exception, something is expected here, let me take a short look.
