### ISSUE TITLE
Blank connection when deployed?

### ISSUE THREAD

**Issue by joeyeng** [jeffhollan/LogicAppTemplateCreator#33]
After deploying the generated template my connection had blank values:

```
"$connections": {
        "value": {
            "azureblob_1": {
                "connectionId": "",
                "connectionName": "",
                "id": ""
            }
        }
    }
```
Here's how it was defined in the template:
```
"parameters": {
          "$connections": {
            "value": {
              "azureblob-1": {
                "id": "[concat('/subscriptions/',subscription().subscriptionId,'/providers/Microsoft.Web/locations/',parameters('logicAppLocation'),'/managedApis/azureblob')]",
                "connectionId": "[resourceId('Microsoft.Web/connections', parameters('azureblob-1_name'))]",
                "connectionName": "[parameters('azureblob-1_name')]"
              }
            }
          }
        }
```

Did I do something wrong or is this a known limitation?

**Comment by MLogdberg** [comment]
Hi, not sure exactly how you mean, was the lower code snippet how the ARM template looked like when deploying? Since that seems correct according too me.

**Comment by joeyeng** [comment]
The upper snippet is how it looks in code view when the LA was deployed.
The lower snippet is what was generated by the tool.

**Comment by MLogdberg** [comment]
Wow that was a new one, never seen that before...
Is it the same if you try a new Logic App? Any special restrictions that you have? Using power shell to deploy or VSTS?

**Comment by joeyeng** [comment]
This was a new LA (first time deploying it to this subscription and resource group at least). I don't know of any special restrictions (I wasn't the one who created the resource group).. anything I should look for in particular? Using VSTS to deploy.

**Comment by joeyeng** [comment]
@MLogdberg Looking at the workflow definition of the generated template I see the connection referred to as azureblob_1: `@parameters('$connections')['azureblob_1']['connectionId']`, but the parameters lists the name as azureblob-1. One uses underscore and one uses dash. This seems like a problem. Or is that okay?

**Comment by joeyeng** [comment]
@MLogdberg I've got a fix. PR coming soon.

**Comment by MLogdberg** [comment]
Sounds good!

**Comment by joeyeng** [comment]
PR https://github.com/jeffhollan/LogicAppTemplateCreator/pull/35
