### ISSUE TITLE
Null FTP parameters

### ISSUE THREAD

**Issue by lfalck** [jeffhollan/LogicAppTemplateCreator#37]
Hi!

These FTP parameters are generated with null values which causes the ARM template deploy to fail:

ftp_closeConnectionAfterRequestCompletion (default is false)
ftp_password (should be empty string or dummy value?)

Best regards,
Ludvig Falck

**Comment by lfalck** [comment]
You can close this, not sure if it was fixed or if i did something weird when it happened but i am getting correct (non null) values for `ftp_closeConnectionAfterRequestCompletion` and `ftp_password` now.

Thanks!

**Comment by MLogdberg** [comment]
Thanks for update!
