### ISSUE TITLE
Error in getting the LogicApp Template

### ISSUE THREAD

**Issue by rohitravva** [jeffhollan/LogicAppTemplateCreator#65]
Hello - Iam trying to download the logicapp template. I followed the exact steps that are provided in the description. I get the below error when i try to download 

cmd> Get-LogicAppTemplate

cmdlet Get-LogicAppTemplate at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
LogicApp: XXXXXXXXXXXXXXx-XXXXXXXXXx
ResourceGroup: RG-Dev-xxx
SubscriptionId: eexxxxxxxx-1xxxxx-4xxx-bc24-eb6xxxxxcfa
Get-LogicAppTemplate : Aggregation Exception thrown, One or more errors occurred., first Exception message is: Value
cannot be null.
Parameter name: s, for more information read the output file.
At line:1 char:1
+ Get-LogicAppTemplate
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LogicAppTemplate], Exception
    + FullyQualifiedErrorId : System.Exception,LogicAppTemplate.GeneratorCmdlet

Any Inputs would be really helpful.

**Comment by MLogdberg** [comment]
Not been any updates o this so closing, sorry for no answear but it's usually a user right thing.
