### ISSUE TITLE
 Get-LogicAppTemplate throws Aggregation Exception

### ISSUE THREAD

**Issue by guruaravinth** [jeffhollan/LogicAppTemplateCreator#75]
Hi,
While trying to export the deployment template for a LogicApp, we are facing the below error:

Get-LogicAppTemplate : Aggregation Exception thrown, One or more errors occurred., first Exception message is: Object reference not set to an instance of an object., for more information read
the output file.
At line:1 char:1
+ Get-LogicAppTemplate -LogicApp TEST_EXPORT -ResourceGroup <MyResGrp> - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LogicAppTemplate], Exception
    + FullyQualifiedErrorId : System.Exception,LogicAppTemplate.GeneratorCmdlet

As suggested in other similar issues, I tried adding the tenant. But even after using the Tenant, it's throwing the same error. I am guessing this has to do with the SQL server API connection used in my Logic App. 

I was able to export LogicApps successfully that are using old version of SQL server API connections. But when I am using new API connection version that lets us pick the Authorization method (like Azure AD, Windows, etc.)  I am facing this error.

Can you please look into this? 

Thanks.

**Comment by lEnforceRl** [comment]
Are you using ARMClient to download multiple templates without the script asking you to login for every template? If the error appears random (sometimes the template is downloaded, sometimes not) I might have a solution. Keep in mind that ARMClient might fail sometimes randomly. I got around the issue by using try()...catch() method to repeat the download if the first one returns an error.

**Comment by lEnforceRl** [comment]
Are you trying to download multiple templates with ARMClient? If so, I had the same error randomly appear to me as well. I tried lot's of things but I just ended up using a try()...catch() method twice inside my script in order to repeat the download when it fails the first time. Not a perfect solution, but it works...

**Comment by MLogdberg** [comment]
Hi, if it’s sql make sure you have the latest version since introducing changes to version we missed a change of datastructure in the api.

**Comment by guruaravinth** [comment]
Thanks for the reply. I pulled the latest version and it's working now!!
