### ISSUE TITLE
Template file is empty after running Get-LogicTemplate

### ISSUE THREAD

**Issue by saikovvuri** [jeffhollan/LogicAppTemplateCreator#77]
Hello, 
I am trying to learn how the template extraction works. 

I create a logic app using the template - https://github.com/Azure/azure-quickstart-templates/tree/master/101-logic-app-create

Then i ran the following command
armclient token $SubscriptionId | Get-LogicAppTemplate -LogicApp $LogicApps -ResourceGroup $ResourceGroup -SubscriptionId $SubscriptionId -TenantName $TenantName -Verbose | Out-File logic-app-template.json

However I see an empty file in the directory

**Comment by MLogdberg** [comment]
Do you get an error when executing the command?

**Comment by saikovvuri** [comment]
Hey Mattias, 
Thank for following up.  No errors.  It runs and instantly completes which tell me it did pass some of the condition in the code. just generates a 0B output file. 

Regards,
Sai

**Comment by MLogdberg** [comment]
Strange, should work just fine and if not provide an error. Looks like it's not finding any content, can you look into the Logic App in the portal to see if it's showing any content?

**Comment by saikovvuri** [comment]
Hey Mattias, 
yes Logic app is working , can see the template, download it .

**Comment by saikovvuri** [comment]
not sure why the template generation wont work

**Comment by MLogdberg** [comment]
That is strange, are you sure all paramters are correct? and no errors in the extraction?

**Comment by MLogdberg** [comment]
Closing this since we don't get this any closer.
