### ISSUE TITLE
Clarify README

### ISSUE THREAD

**Issue by jawn** [jeffhollan/LogicAppTemplateCreator#85]
The README.md contains:

> For extraction with KeyVault reference liks created use:

Can you clarify what the liks part means?

**Comment by MLogdberg** [comment]
Hi,

If you want the parameter file generated with Key Vault markup use the satatement:
Get-ParameterTemplate -TemplateFile $filenname -KeyVault Static | Out-File $filennameparam

You will then get a sample of how the linking to a key vault will look like in the ARM template parameter file. (looks similar but not the same as bellow)
"paremeterName": {
        "reference": {
          "keyVault": {
          "id": "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.KeyVault/vaults/<vault-name>"
          },
          "secretName": "ExamplePassword"
        }
      }

Read more on:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/key-vault-parameter?tabs=azure-cli#reference-secrets-with-static-id

**Comment by jawn** [comment]
Thanks for the sample usage. However, it still is not clear to me whether "liks" is a typo or a thing.

**Comment by MLogdberg** [comment]
Ahh thanks, typo to me I’ll update it. 

Med vänlig hälsning,
Mattias

Skickat från min iPhone
