### ISSUE TITLE
Wrong servicebus-related parameter names

### ISSUE THREAD

**Issue by evandeworp** [jeffhollan/LogicAppTemplateCreator#86]
In LogicAppTemplateCreator/LogicAppTemplate/TemplateGenerator.cs, there's section of code:

                        else if (concatedId.EndsWith("/servicebus')]"))
                        {
                            var namespace_param = AddTemplateParameter($"servicebus_namespace_name", "string", "REPLACE__servicebus_namespace");
                            var sb_resource_group_param = AddTemplateParameter($"servicebus_resourceGroupName", "string", "REPLACE__servicebus_rg");
                            var servicebus_auth_name_param = AddTemplateParameter($"servicebus_accessKey_name", "string", "RootManageSharedAccessKey");

                            connectionParameters.Add(parameter.Name, $"[listkeys(resourceId(parameters('servicebus_rg'),'Microsoft.ServiceBus/namespaces/authorizationRules', parameters('servicebus_namespace_name'), parameters('servicebus_auth_name')), '2017-04-01').primaryConnectionString]");

                        }
    
The above code creates 3 parameters: "servicebus_namespace_name", "servicebus_resourceGroupName" and "servicebus_accessKey_name".

But the next line uses parameters with the same purposes but different spellings "servicebus_rg" and "servicebus_auth_name:

                            connectionParameters.Add(parameter.Name, $"[listkeys(resourceId(parameters('servicebus_rg'),'Microsoft.ServiceBus/namespaces/authorizationRules', parameters('servicebus_namespace_name'), parameters('servicebus_auth_name')), '2017-04-01').primaryConnectionString]");

The template that's generated looks like:

    "servicebus_namespace_name": {
      "type": "string",
      "defaultValue": "REPLACE__servicebus_namespace"
    },
    "servicebus_resourceGroupName": {
      "type": "string",
      "defaultValue": "REPLACE__servicebus_rg"
    },
    "servicebus_accessKey_name": {
      "type": "string",
      "defaultValue": "RootManageSharedAccessKey"
    },

and:

        "displayName": "[parameters('servicebus-2_displayName')]",
        "parameterValues": {
          "connectionString": "[listkeys(resourceId(parameters('servicebus_rg'),'Microsoft.ServiceBus/namespaces/authorizationRules', parameters('servicebus_namespace_name'), parameters('servicebus_auth_name')), '2017-04-01').primaryConnectionString]"
        }

**Comment by MLogdberg** [comment]
Thanks for reporting this, I'll look in to it!

**Comment by MLogdberg** [comment]
Hi, this should be solved with Merge: #88
Please verify.

**Comment by evandeworp** [comment]
This fixed issue #86. Thank you.
