### ISSUE TITLE
httpTriggerUrl gets wrong URL upon extraction

### ISSUE THREAD

**Issue by linuswaerner** [jeffhollan/LogicAppTemplateCreator#96]
I've noticed an anomaly in the extraction of the httpTriggerUrl object when using a HTTP trigger.

This is what we deploy:
```

  "outputs": {
    "httpTriggerUrl": {
      "type": "string",
      "value": "[listCallbackURL(concat(resourceId(resourceGroup().name,'Microsoft.Logic/workflows/', parameters('logicAppName')), '/triggers/request'), '2016-06-01').value]"
    }
  }
```

If I extract it again after deploy, this is what I get:
```
  "outputs": {
    "httpTriggerUrl": {
      "type": "string",
      "value": "[listCallbackURL(concat(resourceId(resourceGroup().name,'Microsoft.Logic/workflows/', parameters('logicAppName')), '/triggers/manual'), '2016-06-01').value]"
    }
  }
```
Please notice the change of '/triggers/request' to '/triggers/manual'.
The workaround so far is to manually replace the 'manual' route with 'request', before commit.

**Comment by MLogdberg** [comment]
Thanks for reporting! This should be fixed now and a new version should be up release to PowerShell Gallery now

**Comment by MLogdberg** [comment]
This is solved, open if not agreeing :)
